# Generated by Django 2.0 on 2018-05-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20180520_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
