# Generated by Django 2.0 on 2018-05-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180520_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='parent',
            field=models.CharField(default='', max_length=200),
        ),
    ]
