# Generated by Django 2.0 on 2018-05-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_datasource_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='parent',
            field=models.CharField(max_length=200),
        ),
    ]
