# Generated by Django 2.0 on 2018-05-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180520_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='backends',
            name='name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
