# Generated by Django 2.0 on 2018-05-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180520_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='min_update_delay',
            field=models.IntegerField(null=True),
        ),
    ]
