# Generated by Django 2.0 on 2018-05-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180520_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='min_update_delay',
            field=models.CharField(default='', max_length=200),
        ),
    ]
