# Generated by Django 2.0 on 2018-05-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20180520_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='min_update_delay',
            field=models.CharField(max_length=200),
        ),
    ]
