# Generated by Django 2.0 on 2018-05-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20180520_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backends',
            name='sleep_time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sortinghat',
            name='sleep_for',
            field=models.CharField(max_length=200),
        ),
    ]
