# Generated by Django 2.0 on 2018-05-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20180520_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup',
            name='phases',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='sortinghat',
        ),
        migrations.AddField(
            model_name='setup',
            name='affiliate',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='autoprofile',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='autorefresh',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='bots_names',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='collection',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='database',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='enrichment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='host',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='identities',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='load_orgs',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='matching',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='name',
            field=models.CharField(default='setup', max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='orgs_file',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='panles',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='sleep_for',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='unaffiliated_group',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='setup',
            name='es_collection',
        ),
        migrations.AddField(
            model_name='setup',
            name='es_collection',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='setup',
            name='es_enrichment',
        ),
        migrations.AddField(
            model_name='setup',
            name='es_enrichment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='setup',
            name='projects_file',
            field=models.CharField(default='', max_length=200),
        ),
    ]
