# Generated by Django 2.0 on 2018-05-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20180520_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setup',
            old_name='panles',
            new_name='panels',
        ),
    ]
