# Generated by Django 2.0 on 2018-05-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_repository_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='parent',
            field=models.CharField(max_length=200),
        ),
    ]
