# Generated by Django 2.0 on 2018-05-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20180520_2302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Es_Collection',
        ),
        migrations.DeleteModel(
            name='Es_Enrichment',
        ),
        migrations.DeleteModel(
            name='Phases',
        ),
        migrations.DeleteModel(
            name='Sortinghat',
        ),
        migrations.AddField(
            model_name='backends',
            name='latest_items',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='backends',
            name='sleep_for_rate',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='backends',
            name='studies',
            field=models.CharField(default='', max_length=200),
        ),
    ]
