# Generated by Django 2.0 on 2018-05-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20180521_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backends',
            name='latest_items',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='backends',
            name='sleep_for_rate',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='backends',
            name='studies',
            field=models.CharField(max_length=200),
        ),
    ]
